### PR TITLE
feat(buck): add the non interactive flag to the init command

### PR DESCRIPTION
**Pull request by mmuenker**
Add the flag --non-interactive. Foreach interactive option the default value will be used

The `--non-interactive` flag allows the execution of the init command in a headless environment. Like a CI.

### CODE REVIEW

**Comment by sanderpick** [comment]
Hey @mmuenker, you can achieve the same behavior by using the existing flags. For example, supply the `name` flag to skip the name prompt, and use the `private` flag to skip the encryption prompt.

**Comment by mmuenker** [comment]
> Hey @mmuenker, you can achieve the same behavior by using the existing flags. For example, supply the `name` flag to skip the name prompt, and use the `private` flag to skip the encryption prompt.

That is correct, but this is very inconvenient.
Generally, it would be a good idea to introduces the `--non-interactive` flag on a global level. The user could be sure that every prompt is skipped and the default value is used. Else the user has to consult the documentation to finger out which flags must be set to prevent the prompts.

**Comment by sanderpick** [comment]
Hey @mmuenker, I hear you. The problem with a catchall "non interactive" flag, is that if we change any of the defaults, users' scripts will be broken. I would rather users go to the trouble of consulting `--help` to learn how to provide values explicitly.

**Comment by sanderpick** [comment]
Closing due to inactivity. Feel free to resubmit if you want to keep working on a solution here.

**Pull request closed without merging**
