### PR TITLE
feat(buck): extend command init with the format flag

### PR DESCRIPTION
**Pull request by mmuenker**
Add the flag --format. The flag --format accepts a string to define the output format.
Add support for the format 'json'.

### CODE REVIEW

**Comment by sanderpick** [comment]
Nice! Instead of adding the `format` flag to each `buck` subcommand, you can add it to the root command, which will make it available everywhere.

**Comment by mmuenker** [comment]
@sanderpick I have updated the pull requests #484 and #482 to support a global `--format` flag

**Review by sanderpick — COMMENTED** [review]
Hey @mmuenker, sorry for the delay here. This looks good for the init command. If we're not going to handle the format flag for the other commands just yet, I think it makes more sense to add it separately to each sub command.

**Comment by sanderpick** [comment]
Closing due to inactivity. Feel free to resubmit if you want to keep working on a solution here.

**Pull request closed without merging**
